### ISSUE TITLE
NodeBB SSO email verify enhancement

### ISSUE THREAD

**Issue by vicnguyenqt** [julianlam/nodebb-plugin-sso-oauth#105]
Hi developers & maintainers,

Thanks for keeping this plugin update-to-date 👍 
I have a proposal on whether we could verify users from SSO. 
There is already a related topic has been discussed in [NodeBB community](https://community.nodebb.org/topic/16445/turning-off-email-verification-for-sso/1) already, but there is still a small problem.

### Problem & scenario
Example if the user uses SSO to log in. As an admin, I would like to find that user from ACP, e.g: to delete account.
I search for that email address and **no user found**. I checked the logic from NodeBB core and it's seems that [this logic](https://github.com/julianlam/nodebb-plugin-sso-oauth/blob/master/library.js#L212) cannot trigger user object creation.
If I go to the user profile, also no email history is found!

### Suggestion (or what I've done)
From this plugin, we could properly write auth logic [here](https://github.com/julianlam/nodebb-plugin-sso-oauth/blob/master/library.js#L190). Let's say I would tell user to verify themself first:
`if(typeof data.email_verified === "undefined" || data.email_verified === false) {
            var err_a = new Error('Email address is not verified');
            err_a.loginheader =  'Your email address has not yet been verified.'
            err_a.logintext = 'Check your email for further instructions. <a href="'+config.login_domain+'/confirm_resend?redirect_uri='+config.url+'/login">Resend the instructions to your email</a>';
			console.log(err_a)
			return callback(err_a, null);
            }`

Eventually, it makes sense that we should verify them as a verified user [here](https://github.com/julianlam/nodebb-plugin-sso-oauth/blob/master/library.js#L212) by adding below code.
`await User.setUserField(uid, 'email', payload.email);
await UserEmail.confirmByUid(uid);`

Now if the user enters the Forum, new joiners got email verified and also we could find him from ACP.

P/s: I'm not sure whether this improvement should be done from NodeBB core, or even here...It's open discussion.

I used NodeBB 2.8.0 with the latest SSO plugin.

**Comment by julianlam** [comment]
The issue is whether the plugin should trust emails that come from the OAuth server. That's not a determination that you or I can make because anyone implementing a login bridge using this template could connect to any OAuth2 server, even ones that don't verify email.

It's in _the end user's best interest_ to be handle emails as though they are untrusted unless explicitly told otherwise. I will add in a config option to trust the email (although the default will be to not trust it — and send out a welcome email accordingly).

**Comment by julianlam** [comment]
I could be wrong, but also `email_verified` is not standard... I wager there's no standard at all for the format and content of the user profile API response :smile: 

So we also can't assume that property... but I can at least provide guidance in the form of comments :shrug:
