### ISSUE TITLE
need for clarification around /callback URL handling

### ISSUE THREAD

**Issue by jessica-mh** [julianlam/nodebb-plugin-sso-oauth#12]
Working on setting up this plugin, and have been able to get to the point where my SSO endpoint is passing data back to the callback URL, but is just receiving a new auth request redirect in return. I have been able to find the prototype/function for handling the callbacks. Where is this set up? Much appreciated.

**Comment by jessica-mh** [comment]
Hey- I solved this issue and just wanted to compliment you on the quality of code in NodeBB itself. Considering this will be the only authentication we will use (it's for our web store's forum), I just re-wrote the login functionality and created routes to handle the callback, which proved much less convoluted for my needs

**Comment by ayxos** [comment]
Can you share those mods with us?
