### ISSUE TITLE
InternalOAuthError is undefined

### ISSUE THREAD

**Issue by john-goldsmith** [julianlam/nodebb-plugin-sso-oauth#13]
```
error: ReferenceError: InternalOAuthError is not defined
```

https://github.com/julianlam/nodebb-plugin-sso-oauth/blob/master/library.js#L74
https://github.com/julianlam/nodebb-plugin-sso-oauth/blob/master/library.js#L96

Needs something like this:

`var InternalOAuthError = module.require('passport-oauth').InternalOAuthError;`

**Comment by julianlam** [comment]
Apologies for the delay, I did not see this issue opened. If you are still having problems please reply back and I will reopen, thanks!

**Comment by julianlam** [comment]
Oh hang on, this is a legit bug, thanks, I'll take a look.

**Comment by julianlam** [comment]
Ah, it looks like I've removed the faulty code awhile ago :smile: 

Thanks for reporting!
