### ISSUE TITLE
Patreon.com integration

### ISSUE THREAD

**Issue by gwhrengineering** [julianlam/nodebb-plugin-sso-oauth#15]
Hello everyone,
I am currently trying to use the nodebb single sign-on oAuth2 plugin to integrate patreon (www.patreon.com) with nodebb.  I followed the comments on gihub and used the oath plugin but
I cannot seem to get it to work correctly.  I changed the library.js file with the following information

type: 'oauth2', // Either 'oauth' or 'oauth2'
name: 'patreon', // Something unique to your OAuth provider in lowercase, like "github", or "nodebb"
oauth: {
requestTokenURL: '',
accessTokenURL: '',
userAuthorizationURL: '',
consumerKey: '',
consumerSecret: ''
},
oauth2: {
authorizationURL: 'http://patreon.com/oauth2/authorize',
tokenURL: 'https://api.patreon.com/oauth2/token',
clientID: 'xxxxxx',
clientSecret: 'yyyyyy'
},
userRoute: 'https://api.patreon.com/oauth2/api/current_user' // This is the address to your app's "user profile" API endpoint (expects JSON)
However, the url created does not seem to work and I get a mismatch resolve url error.  When I paste the url into the browser, the give access page shows but once I
grant access, I get an error saying the resolve url does not exist.  I was wondering if anyone had any ideas on how to make this work.
Thanks

**Comment by julianlam** [comment]
Hey @gwhrengineering -- this plugin is a skeleton plugin to connect to a generic OAuth2 provider. It can work with Patreon, but it is _probably_ a great deal easier if someone else has done the hard work for you.

To that end, I would recommend starting over (sorry!!) and forking sso-google or sso-facebook instead, and changing the underlying dependency from passport-facebook/google to [passport-patreon](https://www.npmjs.com/package/passport-patreon).

**Comment by julianlam** [comment]
The logic should be straightforward (more straightforward than customizing this plugin, for sure), and ideally the only change you will have to make is changing `PassportFacebook` to `PassportPatreon`.
