### ISSUE TITLE
Don't give instructions to fork and update tokens on line numbers

### ISSUE THREAD

**Issue by marekr** [julianlam/nodebb-plugin-sso-oauth#16]
Because commits like this will appear in github:

https://github.com/hofkensj/nodebb-plugin-sso-oauth/commit/21af9f730600bd456d723d122b2e25e439a956ad

Leaking the client id and secret to the world.
Better off having environment variables or a settings file.

Yea pretty dumb but ugh, the instructions more or less encourage fork and commit

**Comment by julianlam** [comment]
Good suggestion, will be sure to update accordingly :smile:
