### ISSUE TITLE
Please give some introduction how to use this plugin

### ISSUE THREAD

**Issue by bathach95** [julianlam/nodebb-plugin-sso-oauth#18]
I am a newbie to nodebb and nodejs as well. I have an web app by Nodejs and I want to login to my web app from nodebb. Can u give me some introduction ? You said that we could not find this plugin in plugin page so how can we "Activate this plugin from the plugins page" ? Can you give me an example ? I really thank you

**Comment by julianlam** [comment]
The readme and code itself in library.js are sufficient to get you started. We can also build the plugin for you for a fee, please contact us at sales@nodebb.org

**Comment by julianlam** [comment]
Unfortunately as this is a free plugin, I do not have the bandwidth to provide guidance free-of-charge.
