### ISSUE TITLE
Feature Request: Reword the title

### ISSUE THREAD

**Issue by donho** [julianlam/nodebb-plugin-sso-oauth#24]
If the login page is disabled for the security reason and uses only nodebb-plugin-sso-oauth for the authentication, such settings make login screen shows “Alternative Logins” (image link):
https://community.notepad-plus-plus.org/assets/uploads/files/1585117401737-a18ec50a-5bb0-4840-9a67-6f999df4c201-image.png

It makes kind of confusion for users of NodeBB.
Could you consider to set **Available Logins** instead of “Alternative Logins” in this module if the native login feature in NodeBB is disabled?

**Comment by julianlam** [comment]
Hm... it looks like you're actually using a number of different login providers, but not a custom SSO login provided by this plugin.

If you're looking to update the text, perhaps the [customize plugin](https://github.com/NodeBB/nodebb-plugin-customize) can be of help?

**Comment by donho** [comment]
I just installed nodebb-plugin-customize, activated it and restart NodeBB, then run `Plugin->Customize`.
I can see the spinner running, but nothing happens.
It seems nodebb-plugin-customize doesn't work, or do I miss somethings?
