### ISSUE TITLE
admin is always redirect to register/complete with error?

### ISSUE THREAD

**Issue by internalG** [julianlam/nodebb-plugin-sso-oauth#25]
My oauth code work well with all users except admin 1. The admin id is 1 and isadmin = true is set in this plugin. The login is fine, but it's redirected to register/complete when click /admin button. Is something missing here?

**Comment by julianlam** [comment]
Apologies for the delay, I did not see this issue opened. If you are still having problems please reply back and I will reopen, thanks!
