### ISSUE TITLE
Turn into a template repository

### ISSUE THREAD

**Issue by oplik0** [julianlam/nodebb-plugin-sso-oauth#27]
This repository is basically a perfect example of what repository templates were created for, so why not turn it into one :)

There are two main advantages here:
1. It's easy to create new repository based on a template more than once per account/organization (you can only create one fork per account/org. Then you have to create new repositories copying the content of this one instead).
2. It tells the users that this plugin doesn't work out of the box, but needs to be customized to make it work ("Template" next to repository name on its page)

And since it's just one checkbox in settings it took more time to write this issue that it should take to solve it.

More information:
[docs on creating template repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)
[docs on using template repositories to create new ones](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template)
[announcement post](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/)

**Comment by julianlam** [comment]
ok :smile:  done
