### ISSUE TITLE
How i change icon for Alternative Logins?

### ISSUE THREAD

**Issue by surajdalvi** [julianlam/nodebb-plugin-sso-oauth#9]
I want to change the icon for Alternative Logins. I update code which is present in login.tpl
But it not works. 
So can you please help me how I change that icon. I want to add an image.

**Comment by surajdalvi** [comment]
please help me to change icon?

**Comment by julianlam** [comment]
You can change the icon here: https://github.com/julianlam/nodebb-plugin-sso-oauth/blob/81e2826ad00cae19f11a61e9ad92ebfa1299e10e/library.js#L127

**Comment by surajdalvi** [comment]
But i want to add my custom image how i do that?

**Comment by surajdalvi** [comment]
I have one image which is present in some URL. I want to set that image as an icon, how I do that? please help me

**Comment by julianlam** [comment]
I would recommend using custom css to select for it and replace it with an
image of your choice (using the :after pseudo selector)

**Comment by surajdalvi** [comment]
I tired  to put my custom CSS code on public/stylesheet.css file,  but as I restarted the NodeBB server that custom part get override by old code, I am unable to put my custom code in files, can You please suggest me where I can put my  custom code please give me a simple example for it?

**Comment by surajdalvi** [comment]
Thanks, I done that changes now I can use my custom image as icon. now I want change title Alternative Logins to my custom title how I do that please help me?

**Comment by julianlam** [comment]
You'll have to alter the theme itself, as this string is hardcoded.
